--=============================
-- BUSINESS ANALYSIS QUESTIONS 
--=============================================================

-- 1.HOW MUCH OF NETFLIX CATALOG CONSISTS OF MOVIES AND TV SHOWS ?

SELECT 
TYPE ,
COUNT ( *) AS TOTAL_TYPE 
FROM Netflix
GROUP BY TYPE 

-- BUSINESS INSIGHT 
-- 1. NETFLIX MAJORITY IS WITH MOVIES 
--2. TV SHOWS ARE COMPARITIVLY LESSER THEN THE MOVIES 

--=======================================================================

-- 2. FIND THE TOP 10 COUNTRIES WITH THE HIGHEST NUMBER OF TITLES AVAILABLE ON NETFLIX ?

SELECT TOP 10 
COUNTRY ,
COUNT (*) AS TOTAL_TITLES 
FROM NETFLIX 
GROUP BY COUNTRY 
ORDER BY TOTAL_TITLES DESC

--BUSINESS INSIGHT 
--1. US HAVE THE HIGHEST NUBER OF TITLES AVAILABLE ON NETFLIX 
--2. MAXICO HAVE THE LOWEST TITLES AVAILABLE ON NETFLIX 

--===========================================================================

--3 . WHICH 10 GENRES APPEAR MOST FREQUENTLY IN THE NETFLIX CATALOG ?

SELECT TOP 10 LISTED_IN  
FROM NETFLIX 

--BUSINESS INSIGNT 
-- 1 . DOCUMENTARIES ARE THE  MOST FREQUENTLY IN THE NETFLIX CATALOG 
--2 .COMEDIES AND DRAMAS ARE THE LOWEST FREQUENTLY IN THE NETFLIX CATALOG  

--=============================================================================
--4 .HOW MANY TITLES WERE ADDED EACH YEAR AND WHICH YEAR HAD THE HIGHEST GROWTH ?
  
 SELECT TOP 1
 YEAR(DATE_ADDED) AS Added,
 COUNT(*) AS TOTAL_TITILES 
FROM NETFLIX 
WHERE DATE_ADDED IS NOT NULL
GROUP BY YEAR(DATE_ADDED)
ORDER BY TOTAL_TITILES DESC;

--BUSINESS INSIGHT 
-- 1. 2016 TITLES ADDED EACH YEAR 
--2 . 2019 WAS THE HIGHEST GROWTH 

--=============================================================================
--5 . WHICH  DIRECTORS HAVE PRODUCED THE HIGHEST NUMBER OF TITLES ON NETFLIX ?

SELECT TOP 5
DIRECTOR ,
COUNT (*) AS TOTAL_TITLES 
FROM NETFLIX 
WHERE DIRECTOR IS  NOT NULL 
GROUP BY DIRECTOR 
ORDER BY TOTAL_TITLES DESC

---- BUSINESS INSIGHT 
--1 . RAJHIV CHILAKA IS THE HIGHEST PRODUCED DIRECTOR OF TITLES ON NETFLIX WITH 19 TOTAL TITLES 
--======================================================================================
