--=========================================== DECISION MAKING QUESTIONS=========================================================

--WHICH 10 GENRES SHOULD NETFLIX FOCUS ON IF THE GOAL IS TO INVEST IN THE MOST POPULAR CONTENT CATOGORIES ?
WITH GENRE_COUNT AS
( 
SELECT 
TRIM(VALUE)  AS GENRE,
COUNT (*)  AS TOTAL_TITLES 
FROM NETFLIX 
CROSS APPLY STRING_SPLIT(LISTED_IN, ',')
GROUP BY TRIM(VALUE) 
) 
SELECT TOP 10 
GENRE,
TOTAL_TITLES 
FROM GENRE_COUNT 
ORDER BY TOTAL_TITLES DESC 

----------------------------------------------BUSINESS INSIGHT--------------------------------------------------------

--1 .NETFLIX CAN FOCUS TO INVEST IN INTERNATIONAL MOVIES  AND DRAMAS AS THEY ARE HIGHLY REVENUE COLLECTOR 
-- 2. ROMANTIC MOVIES CAN BE IMPROVED IF THEY FOCUS ON THESE 
--3. NETFLIX CAN CONTINUE INVESTING IN THESE SECTORS WHILE CONTINUE TESTING NEW CATALOGS 

--=======================================================================================================================
--2 . WHICH 5 COUNTRIES HAVE THE LOWEST REPRESENTATION IN NETFLIX CATALOG AND COUNLF BE CONSIDERED FOR INCREASED LOCAL CONTNT  INVESTMENT ? 

WITH COUNTRY_COUNT AS ( 
SELECT 
TRIM(VALUE) AS COUNTRY ,
COUNT (*) AS TOTAL_TITLES
FROM NETFLIX 
CROSS APPLY STRING_SPLIT (COUNTRY, ',')
WHERE COUNTRY IS NOT NULL 
GROUP BY TRIM(VALUE)
) 
SELECT TOP 5 
COUNTRY ,
TOTAL_TITLES 
FROM COUNTRY_COUNT
ORDER BY TOTAL_TITLES ASC

----------------------------------------------BUSINESS INSIGHT--------------------------------------------------------
--1 . MORE LOCAL CONTENT CAN IMPROVE THE GEOGRAPHIOCAL ENGAGEMENT OF PEOPLE
---2 . NETFLIX CAN EPLORE MORE COUNTRIES TO BOOST THERE RENEVNUE
---3 . NETFLIX SHOULD INVERST IN THIS GROUP TO MAKE A IMPROVEMENT WHICH CAN ALSO LEAD TO A GOOD INVESTMENT AND FOR THE FUTURE 

--=======================================================================================================================
-- 3. WHICH COUNTRIES HAVE A HIGHER PROPOTION OF TV SHOWS THAN MOVIES INDICATING AN OPPORTUNITY TO STRENGTHEN TV CONTENT ?
WITH COUNTRY_TYPE AS
(
SELECT
TRIM(VALUE) AS COUNTRY,
TYPE,
COUNT(*) AS TITLE_COUNT
FROM NETFLIX
CROSS APPLY STRING_SPLIT(COUNTRY, ',')
WHERE COUNTRY IS NOT NULL
GROUP BY TRIM(VALUE), TYPE
)
SELECT
COUNTRY,
SUM(CASE WHEN TYPE = 'Movie' THEN TITLE_COUNT ELSE 0 END) AS MOVIES,
SUM(CASE WHEN TYPE = 'TV Show' THEN TITLE_COUNT ELSE 0 END) AS TV_SHOWS
FROM COUNTRY_TYPE
GROUP BY COUNTRY
HAVING SUM(CASE WHEN TYPE = 'TV Show' THEN TITLE_COUNT ELSE 0 END)
> SUM(CASE WHEN TYPE = 'Movie' THEN TITLE_COUNT ELSE 0 END)
ORDER BY TV_SHOWS DESC;

----------------------------------------------BUSINESS INSIGHT--------------------------------------------------------

--NETFLIX CAN FOCUS ON COUNTRIES WHERE TV CONTENT IS ALREADY STONG CAUSE THE VIEWRS OF THAT SPECIFIC COUNTRIRES ARE ALREADY DEVLOPED 
-- NETFLIX CAN STRENGHTHEN TV CONTENT IN COUNTRIES WHERE TV SHOWS ALREADY HAVE A STONG PRESENECE THAN MOVIES 

--=======================================================================================================================
--4. HOW MUCH OF NETFLIX MOVIE CATALOG CONSISTS OF MOVIES REALEASED MORE THAN 20 YEAES AGO ?
SELECT
COUNT(*) AS OLD_MOVIES,
COUNT(*) * 100.0 /
(SELECT COUNT(*)
 FROM NETFLIX
 WHERE TYPE = 'MOVIE ') AS PERCENTAGE
FROM NETFLIX
WHERE TYPE = 'MOVIE '
 AND RELEASE_YEAR < YEAR(GETDATE()) - 20;

 --=======================================================================================================================
 --5.WHICH CONTENT RATINGS DOMINATE NETFLIX CATALOG AND WHICH RATINGS ARE UNDERREPESENETED ?
SELECT
RATING,
COUNT(*) AS TITLE_COUNT
FROM NETFLIX
WHERE RATING IS NOT NULL
GROUP BY RATING
ORDER BY TITLE_COUNT DESC;
----------------------------------------------BUSINESS INSIGHT--------------------------------------------------------

--1 . NETFLIX HAS STRONG MATURE CONTENT 
--2. MORE FAMILY FRINDLY CONTENT COULD HELP ATTRACT FAMILIES AND YOUNGER AUDIENCE 
--3 . NETFLIX CAN ACCTUALY BALALNCE THE VIEWERS AGE BY INCREASING THE CONTENT OF YOUNGER AND FAMILY 

 --=======================================================================================================================
 --6. WHICH YEARS EXPIERECE THE LARGEST INCREASE IN CONTENT ADDITIONS ? WHAT DOES THIS SUGGEST ABOUT NETFLIX CONTENT EXPANSION STRTEGY ?
WITH YEARLY_COUNT AS
(
SELECT
YEAR(DATE_ADDED) AS YEAR,
COUNT(*) AS TITLE_COUNT
FROM NETFLIX
WHERE DATE_ADDED IS NOT NULL
GROUP BY YEAR(DATE_ADDED)
),
YEARLY_INCREASE AS
(
SELECT
YEAR,
TITLE_COUNT,
LAG(TITLE_COUNT) OVER (ORDER BY YEAR) AS PREVIOUS_YEAR_COUNT
FROM YEARLY_COUNT
)
SELECT
YEAR,
TITLE_COUNT,
PREVIOUS_YEAR_COUNT,
TITLE_COUNT - PREVIOUS_YEAR_COUNT AS INCREASE
FROM YEARLY_INCREASE
ORDER BY INCREASE DESC;

--=======================================================================================================================
--7. WHICH GENRES HAVE VERY FEW TTILES AND COULD REPRESENT POTENTIAL CONTENT GAPS ?
WITH GENRE_COUNT AS
(
SELECT
TRIM(VALUE) AS GENRE,
 COUNT(*) AS TITLE_COUNT
FROM NETFLIX
CROSS APPLY STRING_SPLIT(LISTED_IN, ',' )
WHERE LISTED_IN IS NOT NULL
GROUP BY TRIM(VALUE)
)

SELECT TOP 10
 GENRE,
 TITLE_COUNT
FROM GENRE_COUNT
ORDER BY TITLE_COUNT ASC;
----------------------------------------------BUSINESS INSIGHT--------------------------------------------------------

--1. LOW REPRESENTATION IS LIKLY TO BE THE LESS CONTENT AVAILABLE
--2. NETFLIX CAN EXPLORE THE GENRES TO DIVERSIFY ITS CATALOG AND MUST TARGET MORE NEW AUDIENCE 

--=======================================================================================================================
--8 .IF NETFLIX WANTS TO MAINTAIN A BALANCE PORTFOLIO WHICH CONTENT TYPE , GENRE , COUNTRY ,AND RATING SHOULF RECEIVED MORE ATTNTION BASED ON THE CURRENNT CATALOG ? 

-- 1. CONTENT TYPE
SELECT TOP 1
TYPE,
COUNT(*) AS TITLE_COUNT
FROM NETFLIX
GROUP BY TYPE
ORDER BY TITLE_COUNT ASC;


-- 2. GENRE
SELECT TOP 1
TRIM(VALUE) AS GENRE,
COUNT(*) AS TITLE_COUNT
FROM NETFLIX
CROSS APPLY STRING_SPLIT(LISTED_IN, ',')
GROUP BY TRIM(VALUE)
ORDER BY TITLE_COUNT ASC;


-- 3. COUNTRY
SELECT TOP 1
TRIM(VALUE) AS COUNTRY,
COUNT(*) AS TITLE_COUNT
FROM NETFLIX
CROSS APPLY STRING_SPLIT(COUNTRY, ',')
WHERE COUNTRY IS NOT NULL
GROUP BY TRIM(VALUE)
ORDER BY TITLE_COUNT ASC;


-- 4. RATING
SELECT TOP 1
RATING,
COUNT(*) AS TITLE_COUNT
FROM NETFLIX
WHERE RATING IS NOT NULL
GROUP BY RATING
ORDER BY TITLE_COUNT ASC;

----------------------------------------------BUSINESS INSIGHT--------------------------------------------------------

--1.NETFLIX CAN IMPROVE ITS CATALOG BALANCE BY INVESTING MORE IN UNDERREPRESENTED CONTENT TYPE , GENRES , COUNTRIES AND RATINGS 
